"""
Django settings for juguetesonline project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-local-dev-key')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('1', 'true', 'yes')
# Environment indicator: 'development' or 'production'. Optional override via ENVIRONMENT env var.
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development' if DEBUG else 'production')

# Hosts allowed (coma-separados en la variable de entorno)
ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "ventas",
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'useradmin',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}

AUTH_USER_MODEL = 'useradmin.Usuario'

# Custom authentication backend: try useradmin first, then legacy ventas table
AUTHENTICATION_BACKENDS = [
    'useradmin.backends.LegacyVentasBackend',
    'django.contrib.auth.backends.ModelBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise: servir archivos estáticos en producción
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'juguetesonline.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'juguetesonline.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Database: prefer DATABASE_URL (Railway) but keep sensible local default
# Use Railway-provided env vars when available: MYSQL_DATABASE, MYSQLUSER, MYSQLPASSWORD, MYSQLHOST, MYSQLPORT
default_db = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': os.getenv('MYSQL_DATABASE', os.getenv('DB_NAME', 'railway')),
    'USER': os.getenv('MYSQLUSER', os.getenv('DB_USER', 'root')),
    'PASSWORD': os.getenv('MYSQLPASSWORD', os.getenv('DB_PASSWORD', 'PUYkXYrRyjTCfVOMvNPfLAQfZGhdqVSm')),
    'HOST': os.getenv('MYSQLHOST', os.getenv('DB_HOST', 'shinkansen.proxy.rlwy.net')),
    'PORT': os.getenv('MYSQLPORT', os.getenv('DB_PORT', '40112')),
    'OPTIONS': {'charset': 'utf8mb4'},
}

# If a full DATABASE_URL is not provided, allow Railway-style MYSQL_URL or MYSQL_PUBLIC_URL
# to act as the connection string. Otherwise the separate MYSQL_* vars above will be used.
# Accept multiple names for backward compatibility with different Railway exports.
DATABASE_URL_ENV = os.getenv('DATABASE_URL') or os.getenv('MYSQL_URL') or os.getenv('MYSQL_PUBLIC_URL')
if DATABASE_URL_ENV:
    try:
        parsed_db = dj_database_url.parse(DATABASE_URL_ENV)
    except Exception as e:
        # Avoid crashing the app at import time if the provided DATABASE_URL is invalid.
        # Fall back to the component-based vars (already merged into default_db above).
        # Log a visible warning to stderr so deploy logs show the issue.
        import sys
        print(f"WARNING: invalid DATABASE_URL provided, falling back to parts: {e}", file=sys.stderr)
        parsed_db = default_db
    DATABASES = {'default': parsed_db}
else:
    DATABASES = {'default': default_db}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Compressed manifest storage recomendado para producción (WhiteNoise)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [u.strip() for u in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if u.strip()]

# Si necesitas permitir todos (no recomendado en prod) puedes usar la variable env
CORS_ALLOW_ALL_ORIGINS = os.getenv('CORS_ALLOW_ALL_ORIGINS', 'False').lower() in ('1', 'true', 'yes')

# Asegurar que se permitan los headers y métodos comunes usados por el frontend
try:
    from corsheaders.defaults import default_headers, default_methods
except Exception:
    # Si por alguna razón corsheaders no está disponible en tiempo de import,
    # definimos valores por defecto razonables para evitar fallos de importación.
    default_headers = (
        'accept', 'accept-encoding', 'authorization', 'content-type',
        'dnt', 'origin', 'user-agent', 'x-csrftoken', 'x-requested-with',
    )
    default_methods = ('DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT')

# Permitir headers que el frontend necesita (Authorization, Content-Type, etc.)
CORS_ALLOW_HEADERS = list(default_headers) + [
    'authorization',
    'content-type',
]

# Asegurar que los métodos HTTP habituales estén permitidos en preflight
CORS_ALLOW_METHODS = list(default_methods)

# Si el frontend usa cookies de sesión, habilitar credenciales. Para JWT no es necesario,
# pero no causa problemas si está en False.
CORS_ALLOW_CREDENTIALS = False

# AUTH_USER_MODEL ya está definido más arriba; mantener el valor existente

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Media files (user-uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
