# Generated by Django 5.1.7 on 2025-11-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_add_categoria_and_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('figuras', 'Figuras'), ('peluches', 'Peluches'), ('posters', 'Posters'), ('retro', 'Retro'), ('vehiculos', 'Vehículos')], default='figuras', max_length=20),
        ),
    ]
